#
# Copyright (C) 2010, OMBT LLC and Mike A. Rumore
# All rights reserved.
# Contact: Mike A. Rumore, (mike.a.rumore@gmail.com)
#
# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/..
endif

include $(ROOT)/build/makefile.common

SUBDIRS = \
	system \
	atomic \
	errors \
	conversions \
	logging \
	parsing \
	random \
	threads \
	adt \
	complex \
	matrix \
	numerics \
	interpolation \
	gstring \
	timers \
	sockets \
	signals \
	reactors \
	servers \
	distributions \
	files \
	graphs \
	stringutils \
	config \
	logic \
	options \
	preprocessor \
	postprocessor \
	knowledgebase \
	indexing \
	inference \
	provers \
	performance

include $(ROOT)/build/makefile.libsubdirs
