#
# Copyright (C) 2016, OMBT LLC and Mike A. Rumore
# All rights reserved.
# Contact: Mike A. Rumore, (mike.a.rumore@gmail.com)
#
# ROOT = /home/ombt/ombt

ifndef ROOT
ROOT = $(PWD)/..
endif

include $(ROOT)/build/makefile.common

SHELLSCRIPTS = setenv_ombt get.make.implicit.rules 

include $(ROOT)/build/makefile.sh
