######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 23 15:00:12 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += vectorclock.h
SOURCES += testvc.cpp vectorclock.cpp
